version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5434:5432'

volumes:
  db-data: